### PR TITLE
Support ordering templates

### PR DESCRIPTION
**Pull request by amekusa**
エディターにて挿入テンプレートを選ぶ際の、テンプレートの並び順を変更できるようにしてみました。
並び順はページ属性: **順序** ( = `menu_order`) の昇順になります。
欲しかったので作ってみました。

### CODE REVIEW

**Comment by miya0001** [comment]
Sorry tests got fail on the Travis CI.
Please update phpunit tests too.

https://travis-ci.org/miya0001/tinymce-templates/builds/56524599

**Comment by amekusa** [comment]
Now, the returned array of `TinyMCE_Templates->get_templates()` is not associative with template IDs
but sequential ordered by `menu_order` attribute.

**Comment by miya0001** [comment]
Thanks!
I'll try testing.

**Comment by miya0001** [comment]
Sorry for late. :)

I tried this pull-request, but it make some problem.

This plugin can add custom template with other plugin like following.
But if I would merge this pull-request, custom template will not work.

https://github.com/miya0001/tinymce-templates-bootstrap-templates

Thanks!

**Comment by amekusa** [comment]
Thank you for reviewing my pull request!

That problem looks be caused by the change of association rule of the array which is returned by `TinyMCE_Templates->get_templates()` as I mentioned above.
So other plugins may have to change it’s way of access the array of TinyMCE templates.

For example, this line.
https://github.com/miya0001/tinymce-templates-bootstrap-templates/blob/master/tinymce-templates-bootstrap-templates.php#L65

I’ll try fix bootstrap-templates unless you are unwilling to adopt this pull request.
I think, an accessor method that returns a specific template by its ID will help to absorb this confliction.

**Comment by miya0001** [comment]
Thanks!! :smile:

**Pull request closed without merging**
